language: ruby
rvm:
  - 2.2

services:
    - docker

install:
  - docker build -t vaclavadamec/consul-config .
  - docker run -d -p 127.0.0.1:80:80 --name consul-config vaclavadamec/consul-config

script:
    - docker ps | grep -q consul-config

notifications:
  email:
    recipients:
      - v.adamec@seznam.cz
    on_success: always
    on_failure: always
